server:
  port: 8888

spring:
  profiles:
    actve: "postgres"
  main:
    banner-mode:
      status: invalid
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000
      minimum-idle: 2
      maximum-pool-size: 5


---

spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/analitLogs
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    show-sql: true